# Get list of station names for a particular line.
GET /resource/8pix-ypme.json?brn=true&$select=station_name&$group=station_name
Host: data.cityofchicago.org
Accept: application/json
X-App-Token: {key}

###
# Get both directions for a selected station.
GET /resource/8pix-ypme.json?brn=true&station_name=Fullerton
Host: data.cityofchicago.org
Accept: application/json
X-App-Token: {key}


###
# Get arrival predictions for a stop.
GET lapi.transitchicago.com/api/1.0/ttarrivals.aspx?key={key}&stpid=30030&rt=brn&outputType=JSON

###
# Get list of stations
GET /resource/8pix-ypme.json?red=true
Host: data.cityofchicago.org
Accept: application/json
X-App-Token: {key}

###
# Test internal get_stations endpoint.
GET http://127.0.0.1:5000/api/blue/stations

###
# Test internal get_stops endpoint.
GET http://127.0.0.1:5000/api/stops
    ?line=blue
    &station=Belmont

###
# Test internal get_arrival_prediction endpoint.
GET http://127.0.0.1:5000/transit/prediction
    ?line=brn
    &stopID=30030